In [6]:
import sys
import platform

import numpy as np
import pandas as pd

try:
    import sklearn
except Exception as e:
    sklearn = None
    print("⚠️ scikit-learn не импортируется:", e)

print("Python:", sys.version.split()[0])
print("Executable:", sys.executable)
print("OS:", platform.platform())

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
if sklearn is not None:
    print("scikit-learn:", sklearn.__version__)


Python: 3.11.14
Executable: /Users/dmitrijkuznecov/anaconda3/envs/mlcourse/bin/python
OS: macOS-26.3-arm64-arm-64bit
NumPy: 2.4.2
Pandas: 3.0.1
scikit-learn: 1.8.0


In [8]:
import numpy as np

np.random.seed(42)

X = np.random.randn(100, 5)

print("X.shape:", X.shape)
print("X.dtype:", X.dtype)
print("First 5 rows:\n", X[:5])

# Задание 3.2
print("\n" + "="*50)
print("СТАТИСТИКИ МАТРИЦЫ X (100×5)")
print("="*50)

# Среднее и стандартное отклонение по всей матрице
mean_all = X.mean()
std_all = X.std()
print(f"Среднее по всей матрице: {mean_all:.4f}")
print(f"Стандартное отклонение по всей матрице: {std_all:.4f}")

# Среднее по каждому столбцу (axis=0)
mean_by_column = X.mean(axis=0)
print("\nСредние значения по столбцам:")
for i, mean_val in enumerate(mean_by_column):
    print(f"  Столбец {i}: {mean_val:.4f}")

# Стандартное отклонение по каждому столбцу
std_by_column = X.std(axis=0)
print("\nСтандартные отклонения по столбцам:")
for i, std_val in enumerate(std_by_column):
    print(f"  Столбец {i}: {std_val:.4f}")

# Минимумы по каждому столбцу
min_by_column = X.min(axis=0)
print("\nМинимальные значения по столбцам:")
for i, min_val in enumerate(min_by_column):
    print(f"  Столбец {i}: {min_val:.4f}")

# Максимумы по каждому столбцу
max_by_column = X.max(axis=0)
print("\nМаксимальные значения по столбцам:")
for i, max_val in enumerate(max_by_column):
    print(f"  Столбец {i}: {max_val:.4f}")

# Для более компактного вывода можно также вывести всё в виде таблицы:
print("\n" + "="*50)
print("СВОДНАЯ ТАБЛИЦА СТАТИСТИК")
print("="*50)
print(f"{'Столбец':<10} {'Среднее':<12} {'Стд.откл.':<12} {'Минимум':<12} {'Максимум':<12}")
print("-"*58)
for i in range(5):
    print(f"{i:<10} {mean_by_column[i]:<12.4f} {std_by_column[i]:<12.4f} "
          f"{min_by_column[i]:<12.4f} {max_by_column[i]:<12.4f}")

X.shape: (100, 5)
X.dtype: float64
First 5 rows:
 [[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]
 [-0.46341769 -0.46572975  0.24196227 -1.91328024 -1.72491783]
 [-0.56228753 -1.01283112  0.31424733 -0.90802408 -1.4123037 ]
 [ 1.46564877 -0.2257763   0.0675282  -1.42474819 -0.54438272]]

СТАТИСТИКИ МАТРИЦЫ X (100×5)
Среднее по всей матрице: 0.0068
Стандартное отклонение по всей матрице: 0.9803

Средние значения по столбцам:
  Столбец 0: -0.0447
  Столбец 1: 0.0770
  Столбец 2: -0.0939
  Столбец 3: 0.1281
  Столбец 4: -0.0322

Стандартные отклонения по столбцам:
  Столбец 0: 0.8958
  Столбец 1: 0.9792
  Столбец 2: 0.9790
  Столбец 3: 0.9547
  Столбец 4: 1.0674

Минимальные значения по столбцам:
  Столбец 0: -1.9521
  Столбец 1: -2.3019
  Столбец 2: -3.2413
  Столбец 3: -1.9133
  Столбец 4: -2.6197

Максимальные значения по столбцам:
  Столбец 0: 2.3147
  Столбец 1: 1.8862
  Столбец 2: 2.1222
  Столбец 3: 3.078